name: Debian package

on: 
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      CI: false

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
      with:
          path: edumeet
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Get eduMEET version
      id: get-version
      run: |
        echo "::set-output name=VERSION::$(cat edumeet/server/package.json | jq -r '.version')"
        
    - name: Build Debian package
      id: build-deb
      run: |
        cd edumeet
        TARGET=/home/runner/package
        cp app/public/config/config.example.js app/public/config/config.js
        cd app && yarn install && yarn build && cd ..
        cd server && yarn install && yarn build && cd ..
        VERSION=${{ steps.get-version.outputs.VERSION }}
        DATE=$(date)
        mkdir -p ${TARGET}/DEBIAN
        mkdir -p ${TARGET}/usr/share/edumeet
        mkdir -p ${TARGET}/lib/systemd/system/
        mkdir -p ${TARGET}/etc/edumeet/
        cp server/config/config.example.js ${TARGET}/etc/edumeet/config.js
        cp server/config/config.example.yaml ${TARGET}/etc/edumeet/config.yaml
        cp -r server/dist/* ${TARGET}/usr/share/edumeet
        cp -r server/node_modules ${TARGET}/usr/share/edumeet
        ln -sf /etc/edumeet/config.js ${TARGET}/usr/share/edumeet/config/config.js
        ln -sf /etc/edumeet/config.yaml ${TARGET}/usr/share/edumeet/config/config.yaml
        mv edumeet.service ${TARGET}/lib/systemd/system/
        touch ${TARGET}/DEBIAN/md5sums
        cat > ${TARGET}/DEBIAN/control <<EOF
        Package: edumeet
        Version: $VERSION
        Maintainer: eduMEET team (${{ github.server_url }}/${{ github.repository }})
        Section: admin
        Date : $DATE
        Architecture: amd64
        Priority: optional
        Description: eduMMET is multiparty web-meetings based on mediasoup and WebRTC
          Packet created from ${{ github.ref_name }} branch, commit:${{ github.sha }}
          Visit ${{ github.server_url }}/${{ github.repository }}/tree/${{ github.ref_name }} for details
        Depends: nodejs (>= 16), redis
        EOF
        #
        cat > ${TARGET}/DEBIAN/postinst <<EOF
        #!/bin/bash
        systemctl daemon-reload
        systemctl enable edumeet
        echo "eduMEET multiparty meeting is installed.\n"
        echo "\n\nClient and server configuration files are in /etc/edumeet directory\n"
        echo "Please visit ${{ github.server_url }}/${{ github.repository }}/tree/${{ github.ref_name }} for configuration details.\n\n"
        echo "\n\nAfter configuration, start service with 'sudo systemctl start edumeet' command.\n\n"
        EOF
        #
        chmod 775 ${TARGET}/DEBIAN/postinst
        cd ${TARGET}/..
        dpkg-deb -Zgzip --build package
        mv /home/runner/package.deb /home/runner/edumeet-$VERSION.deb
        
    - name : Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: edumeet-${{ steps.get-version.outputs.VERSION }}
        path: "/home/runner/edumeet-*.deb"
    
    - name: Add to release assets
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.get-version.outputs.VERSION }}
        files: "/home/runner/edumeet-*.deb"
